techpack: Fix -Werror=restrict
 * techpack/audio/asoc/codecs/wcd9xxx-common-v2.c:368:9: error: 'snprintf' argument 4 overlaps destination object 'buf' [-Werror=restrict]
 * Use scnprintf instead of snprintf